<form data-toggle="validator" role="form">
    <div class="form-group has-feedback">
        <label for="firstname">First name</label>
        <input type="text" class="form-control" id="first_name" placeholder="First name">
        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
    </div>
    <div class="form-group has-feedback">
        <label for="lastname">Last name</label>
        <input type="text" class="form-control" id="last_name" placeholder="Last name">
        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
    </div>
    <div class="form-group has-feedback">
        <label for="email" class="control-label">Email address<span class="text-danger">*</span></label>
        <input type="text" class="form-control" id="email_address" placeholder="Email"
               data-error="Invalid email address format! "
               pattern="^[^\s@]+@[^\s@]+\.[^\s@]+$" required>
        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
        <div class="help-block with-errors"></div>
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>

